version: '2.4'

networks:
  slsr-adm:
    driver: bridge

services:
  db:
    extends:
      file: docker-compose.prod.yml
      service: db
    environment:
      SERVICE_TAGS: dev
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    extends:
      file: docker-compose.prod.yml
      service: app
    environment:
      SERVICE_TAGS: dev
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www/

  www:
    extends:
      file: docker-compose.prod.yml
      service: www
    environment:
      SERVICE_TAGS: dev
    volumes:
      - ./logs/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/static/:/var/www/public
