version: '2.4'

networks:
  slsr-adm:
    driver: bridge

services:
  app:
    extends:
      file: docker-compose.prod.yml
      service: app
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www/

  www:
    extends:
      file: docker-compose.prod.yml
      service: www
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/static/:/var/www/public
