version: '2.4'

networks:
  slsr-adm:
    driver: bridge

volumes:
  logs:
  db-data:

services:
  db:
    image: mariadb:lts
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: db
      SERVICE_TAGS: prod
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/mysql
    networks:
      - slsr-adm
  
  app:
    build:
      context: .
      dockerfile: images/Dockerfile.app
    image: slsr/adm-app:latest
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    depends_on:
      - db
    networks:
      - slsr-adm

  www:
    build:
      context: .
      dockerfile: images/Dockerfile.www
    image: slsr/adm-www:latest
    container_name: www
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: www
      SERVICE_TAGS: prod
    volumes:
      - logs:/var/log/nginx/
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - slsr-adm
