FROM nginx:alpine-slim

WORKDIR /var/www/

# Configure Nginx
COPY --chown=nginx:nginx --chmod=544 nginx.conf /etc/nginx/conf.d/default.conf

# Copy application
#COPY --from=slsr/adm-app:latest --chown=nginx:nginx --chmod=544 /var/www/ ./
COPY --chown=nginx:nginx --chmod=544 public/static/ ./public/static/
