FROM nginx:alpine-slim

WORKDIR /var/www/

# Configure Nginx
COPY --chown=nginx:nginx --chmod=544 nginx.conf /etc/nginx/conf.d/default.conf

# Copy application
COPY --chown=nginx:nginx --chmod=544 public/static/ ./public/
